# This is a basic workflow to help you get started with Actions

name: My Test Workflow
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  my_init_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Echo entering line for my_init_job
        run: echo Entering my_init_job

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script in init_job
        run: |
          echo First multi-line
          echo second multi-line
  my_cond_job:
    needs: my_init_job
    runs-on: ubuntu-latest
    steps:
      - name: Echo entering line for my_cond_job
        run: echo Entering my_cond_job
      - name: Echo if 'main' branch
        if: github.ref == 'refs/heads/main'
        run: echo In main!
      - name: Echo if not 'main' branch
        if: github.ref != 'refs/heads/main'
        run: echo Not in main!
    
